#!/bin/sh


rootPath=`pwd`

./build
													  
for file in bin/isoDE2 bin/convertToisoDEFormatWithIsoforms bin/convert-iso-to-genome-coords bin/extract-isoform-sequences-from-genome bin/fastaToGTF bin/isoboot bin/isoDE_v4.sh bin/isoem bin/isoviz bin/isodecalls bin/SEQ_FREQ.sh
do
	awk -v p="isoDEDir=${rootPath}" '{if (index($0,"isoDEDir=") == 1) print p; else print $0}' $file > ${file}.tmp
	rm ${file}
	mv ${file}.tmp ${file}
	chmod uog+x ${file}

	
done
